export type EventItem = {
  id: string
  category: 'TECHNICAL' | 'NON-TECHNICAL'
  title: string
  type: string
  description: string
  objective: string
  eligibility: string
  needs: string
  venue?: string
  judging: string
  information: string
  teamSize?: string
  prizes?: string
  themes?: string[]
  rules: string[]
}

export const events: EventItem[] = [
  { id: '01', category: 'TECHNICAL', title: 'Glitch Verse', type: 'Codeathon', description: 'Test and improve your programming skills through code typing, debugging, and algorithmic problem-solving challenges.', objective: 'Test and improve participants\' programming skills through code typing, debugging, and algorithmic problem-solving challenges, progressing from basic concepts to advanced coding problems.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Any approved programming language and basic knowledge of programming and algorithms.', judging: 'Participants will be evaluated based on code accuracy, programming efficiency, debugging ability, algorithmic approach, execution speed, and test-case performance.', information: '', rules: ['Participants must use only approved programming languages.', 'Teams can have 1–4 members.', 'Participants must carry their college ID.', 'Internet usage may be restricted according to organizer instructions.', 'Any form of unfair practice may lead to disqualification.', 'Participants must submit their solutions within the allotted time.', 'Judges\' decisions will be final.'] },
  { id: '02', category: 'TECHNICAL', title: 'Mind Spark', type: 'Ideathon', description: 'Turn a real-world problem into an innovative solution and bring it to life with a prototype.', objective: 'Participants are given a theme and must identify a problem within that theme, develop an innovative solution, and demonstrate it through a prototype.', eligibility: 'Students from any discipline may participate.', needs: 'Participants must bring the laptop for presenting your idea\n- A solution idea, prototype/model, and clear presentation explaining the problem, solution, and expected impact.', judging: 'Judges will evaluate:\n- Innovation & originality\n- Feasibility\n- Potential impact\n- Relevance to the given theme\n- Prototype quality\n- Presentation clarity', information: '', themes: ['AI Agents & Automation', 'Sustainability', 'Healthcare', 'Education', 'Cybersecurity', 'Smart Cities', 'Agriculture', 'Accessibility'], rules: ['Teams may have 1–4 members.', 'The solution must be relevant to the given theme.', 'The proposed solution must be original.', 'A prototype/model must be presented.', 'Participants must clearly explain the problem, solution, and impact.', 'Research and external resources must be properly acknowledged.', 'Judges\' decisions will be final.'] },
  { id: '03', category: 'TECHNICAL', title: 'CODE HUNT', type: 'Code Hunt', description: 'A team-based debugging and clue-hunting game where participants must solve a hidden challenge by interacting with other teams. Each team holds a unique clue, and participants must approach different teams, communicate with them, and collect the clues. By connecting and analyzing all the clues, teams must identify the final solution.', objective: 'Test participants\' debugging, logical thinking, communication, teamwork, and problem-solving skills through a team-based clue-hunting challenge.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Multiple teams participate in the game.\n\nEach team is given a different clue.\n\nTeams must interact with other teams to obtain their clues.\n\nThe collected clues must be analyzed and connected.\n\nThe team that solves the challenge correctly first wins.', venue: 'AGRI-Auditorium, Dhanalakshmi Srinivasan Engineering College, Perambalur', judging: 'Teams will be evaluated based on their ability to collect and interpret clues, logical reasoning, communication, teamwork, accuracy, and their ability to identify the final solution.', information: '', prizes: 'Prizes will be awarded to the team that correctly solves the challenge first.', rules: ['Teams must work together throughout the challenge.', 'Each team will receive a different clue.', 'Teams must interact with other participating teams to collect clues.', 'Participants must carefully analyze and connect all collected clues.', 'Teams must identify the final solution using the available clues.', 'The first team to correctly solve the challenge will be declared the winner.'] },
  { id: '04', category: 'TECHNICAL', title: 'VIBE CRAFT', type: 'Vibe Craft', description: 'A real-time vibe coding challenge where teams are given a problem statement on the spot. Participants must understand the given problem, develop a working solution, and demonstrate their creativity and technical skills through rapid coding.', objective: 'Evaluate participants\' ability to quickly understand a problem, develop a working solution, and demonstrate creativity, technical knowledge, and practical coding skills within a limited time.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Teams receive a problem statement at the venue.\n\nThe problem must be solved during the event.\n\nParticipants can use their preferred coding tools and technologies.\n\nTeams are evaluated based on creativity, functionality, technical implementation, and overall solution quality.\n\nThe team with the best solution wins.', venue: 'AGRI-Auditorium, Dhanalakshmi Srinivasan Engineering College, Perambalur', judging: 'Creativity and originality\n\nFunctionality of the solution\n\nTechnical implementation\n\nProblem-solving approach\n\nOverall solution quality', information: '', prizes: 'Prizes will be awarded to the team with the best-performing solution.', rules: ['Teams must solve the given problem during the event.', 'Participants may use their preferred coding tools and technologies.', 'The solution must be developed within the given event time.', 'Teams must demonstrate their working solution when requested.', 'The final solution will be evaluated based on creativity, functionality, technical implementation, and overall quality.'] },
  { id: '05', category: 'NON-TECHNICAL', title: 'BGM Charades', type: 'Music & Movie Recognition', description: 'Hear the tune. Guess the moment. Beat the clock.', objective: 'Identify songs, movies, or iconic scenes by listening to short background-music clips and score maximum points.', eligibility: 'Open to all students with an interest in music, movies, and pop culture.', needs: 'Quick ears, good memory, pop-culture knowledge, and strong teamwork.', judging: 'Points are awarded for correct answers. Speed and accuracy determine the final ranking. In case of a tie, a tie-breaker BGM round will be conducted.', information: '', rules: ['Each team can have 1–4 members.', 'A short BGM/audio clip will be played for each question.', 'Teams must identify the song, movie, or scene represented by the clip.', 'Each question has a limited response time.', 'No mobile phones or external assistance during the event.', 'Teams must maintain silence while the BGM is being played.', 'The team with the highest score wins.'] },
  { id: '06', category: 'NON-TECHNICAL', title: 'SHERLOCK HOLMES', type: 'Sherlock Holmes', description: 'A thrilling mystery-solving game where participants are presented with a mysterious theft case along with a set of carefully designed clues. Using their observation, logical thinking, and deduction skills, participants must analyze the clues, connect the evidence, and identify the thief responsible for the crime.', objective: 'Challenge participants\' observation, logical thinking, analytical reasoning, and deduction skills through an engaging mystery-solving experience.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Participants are given a detailed theft case.\n\nMultiple clues and pieces of evidence are provided.\n\nParticipants must carefully analyze and connect the clues.\n\nUsing logic and deduction, they must identify the thief.\n\nThe participant or team that solves the case correctly wins.', venue: 'AGRI-Auditorium, Dhanalakshmi Srinivasan Engineering College, Perambalur', judging: 'Participants or teams will be evaluated based on their observation, logical reasoning, deduction, accuracy in connecting the evidence, and ability to identify the correct culprit.', information: '', prizes: 'Prizes will be awarded to the participant or team that correctly solves the mystery.', rules: ['Participants must carefully analyze all the clues provided.', 'All clues and evidence must be interpreted using logical reasoning.', 'Participants must identify the thief based on the available evidence.', 'Participants must follow the instructions provided by the event coordinators.', 'The participant or team that correctly solves the case wins.'] },
  { id: '07', category: 'NON-TECHNICAL', title: 'IPL AUCTION', type: 'IPL Auction', description: 'An exciting mock IPL auction game where participants take on the role of franchise owners and build their own dream team. Players are introduced one by one, and teams must strategically bid for them while managing their limited budget.', objective: 'Test participants\' strategic thinking, decision-making, bidding skills, and budget management through an engaging mock IPL auction experience.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Each team is given a fixed virtual budget.\n\nPlayers are introduced for auction one by one.\n\nTeams compete by placing bids for the players they want.\n\nTeams must manage their budget and squad strategically.\n\nThe team that builds the strongest squad within the budget wins.', venue: 'AGRI-Auditorium, Dhanalakshmi Srinivasan Engineering College, Perambalur', judging: 'Teams will be evaluated based on their bidding strategy, budget management, squad planning, decision-making, and overall team composition.', information: '', prizes: 'Prizes will be awarded to the team that builds the strongest squad within the given budget.', rules: ['Each team will receive a fixed virtual budget.', 'Teams must place bids within their available budget.', 'Teams cannot exceed their allocated budget.', 'Players will be introduced one by one during the auction.', 'Teams must make strategic decisions while selecting players.', 'The final squad must be built within the given budget.', 'The team with the strongest overall squad will be declared the winner.'] },
  { id: '08', category: 'NON-TECHNICAL', title: 'HINT CRACKERS', type: 'Hear it. Pass it. Write it. Tell it!', description: 'Hint Crackers is a fun and exciting team communication challenge that tests listening, memory, communication, teamwork, accuracy, and storytelling. A secret keyword travels through four team members, and the final member must turn that word into a creative story.', teamSize: '4 Members per team', objective: 'Test participants’ listening, memory, communication, teamwork, accuracy, creativity, and storytelling abilities through a fun four-stage challenge.', eligibility: 'Open to all college students.', needs: 'Quick thinking, good listening skills, clear communication, teamwork, memory, creativity, and storytelling ability.', judging: 'Teams will be judged based on:\n- Accuracy of the final word\n- Communication and teamwork\n- Speed\n- Creativity\n- Storytelling performance', information: '1. MEMBER 1 – LISTENER\nA secret keyword is shown or given only to the first member. They must carefully remember the keyword.\n\n2. MEMBER 2 – MESSENGER\nMember 1 communicates the keyword to Member 2. The message must be passed accurately without directly showing the written keyword.\n\n3. MEMBER 3 – WRITER\nMember 2 communicates the word to Member 3. Member 3 writes the understood word on the board.\n\n4. MEMBER 4 – STORYTELLER\nMember 4 sees the word written on the board and creates and narrates a short, creative story using that word.', prizes: 'Exciting prizes for the top-performing teams.', rules: ['Each team must have exactly 4 members.', 'The secret keyword is revealed only to Member 1.', 'Participants must follow the assigned order.', 'The keyword must be passed verbally between team members.', 'No writing, mobile phones, or electronic assistance during the communication stages.', 'Member 3 must write the word on the board.', 'Member 4 must create a story using the final word.', 'The story should meaningfully relate to the word.', 'Participants must complete the challenge within the allotted time.', 'Judges’ decision is final.'] },
]

export type Coordinator = {
  name: string
  label: 'HEAD OF DEPARTMENT OF CSE' | 'HOD OF IT' | 'FACULTY COORDINATOR' | 'STAFF COORDINATOR' | 'STUDENT COORDINATOR'
  designation: string
  department: string
  year?: string
  role: string
  bio: string
  contact?: string
  image: string
}

export const coordinators: Coordinator[] = [
  { name: 'Mrs T.GEETHA', label: 'HEAD OF DEPARTMENT OF CSE', designation: 'Head of Department', department: 'CSE', role: 'Academic direction', bio: 'Guiding the academic vision and collaborative spirit behind UNIQUE 2K26.', image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85' },
  { name: 'Mrs S.JAYAPRADHA', label: 'FACULTY COORDINATOR', designation: 'Faculty Coordinator', department: 'CSE', role: 'Faculty coordination', bio: 'Supporting every moving part with care, clarity, and campus experience.', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85' },
  { name: 'Mrs B.DEEPIKA', label: 'FACULTY COORDINATOR', designation: 'Faculty Coordinator', department: 'CSE', role: 'Faculty coordination', bio: 'Connecting teams, mentors, and participants across the symposium.', image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=85' },
  { name: 'Mr R.DEVANAND', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Bringing student energy, ideas, and momentum to the event floor.', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=85' },
  { name: 'Mr R.PAVAN', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Helping every participant find their place in the UNIQUE experience.', image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=85' },
  { name: 'Mr R.SUBASH', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Turning plans into welcoming, thoughtful campus moments.', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=85' },
]

export const itCoordinators: Coordinator[] = [
  { name: 'Mr S.SARAVANAN', label: 'HOD OF IT', designation: '', department: 'IT', role: '', bio: 'Guiding the academic vision and collaborative spirit behind ZENTHRA 2K26.', image: '' },
  { name: 'Ms K.LALITHAVANI', label: 'STAFF COORDINATOR', designation: '', department: 'IT', role: '', bio: 'Supporting every moving part with care, clarity, and campus experience.', image: '' },
  { name: 'Mr P.ARULMOZHI', label: 'STAFF COORDINATOR', designation: '', department: 'IT', role: '', bio: 'Connecting teams, mentors, and participants across the symposium.', image: '' },
  { name: 'Mr S.ARIVU', label: 'STUDENT COORDINATOR', designation: '', department: 'IT', role: '', bio: 'Bringing student energy, ideas, and momentum to the event floor.', image: '' },
  { name: 'Mr M.KARTHIKEYAN', label: 'STUDENT COORDINATOR', designation: '', department: 'IT', role: '', bio: 'Helping every participant find their place in the ZENTHRA experience.', image: '' },
  { name: 'MR S.RAGUL', label: 'STUDENT COORDINATOR', designation: '', department: 'IT', role: '', bio: 'Turning plans into welcoming, thoughtful campus moments.', image: '' },
]

export const faqs = [
  ['What is UNIQUE 2K26?', 'UNIQUE 2K26 is a college symposium bringing students together through technology, creativity, innovation, and entertainment.'],
  ['What is the maximum team size?', 'Teams may have 1–4 members. Individuals are welcome to participate.'],
  ['Can a team participate in more than one event?', 'Yes. Each team may select one Technical event and one Non-Technical event.'],
  ['Can we choose both a technical and non-technical event?', 'Yes. The participation rule is one Technical + one Non-Technical event per team.'],
  ['What are the technical events?', 'Glitch Verse, Mind Spark, RE:UX, and Odyssey Techz.'],
  ['What are the non-technical events?', 'BGM Charades, Connexion, Chithiram – The Visual Saga, and HINT CRACKERS.'],
  ['Can I participate individually?', 'Yes. Individual participation is welcome, and teams may have 1–4 members.'],
  ['How do I register?', 'Use the global REGISTER NOW link near the hero, navbar, or registration section.'],
  ['When will the schedule be announced?', 'The one-day schedule, timings, and venue will be announced soon.'],
  ['Any Issue in Website?', 'If you encounter any issues with the website, please contact us at sakthi88705@gmail.com.']
]
