export type EventItem = {
  id: string
  category: 'TECHNICAL' | 'NON-TECHNICAL'
  title: string
  type: string
  description: string
  objective: string
  eligibility: string
  needs: string
  judging: string
  information: string
  themes?: string[]
  rules: string[]
}

export const events: EventItem[] = [
  { id: '01', category: 'TECHNICAL', title: 'CODEATHON 2026', type: 'Codeathon', description: 'Test and improve your programming skills through code typing, debugging, and algorithmic problem-solving challenges.', objective: 'Test and improve participants\' programming skills through code typing, debugging, and algorithmic problem-solving challenges, progressing from basic concepts to advanced coding problems.', eligibility: 'Open to undergraduate students with a valid college ID.', needs: 'Any approved programming language and basic knowledge of programming and algorithms.', judging: 'Participants will be evaluated based on code accuracy, programming efficiency, debugging ability, algorithmic approach, execution speed, and test-case performance.', information: '', rules: ['Participants must use only approved programming languages.', 'Teams can have 1–4 members.', 'Participants must carry their college ID.', 'Internet usage may be restricted according to organizer instructions.', 'Any form of unfair practice may lead to disqualification.', 'Participants must submit their solutions within the allotted time.', 'Judges\' decisions will be final.'] },
  { id: '02', category: 'TECHNICAL', title: 'MINDSPARK', type: 'Ideathon', description: 'Turn a real-world problem into an innovative solution and bring it to life with a prototype.', objective: 'Participants are given a theme and must identify a problem within that theme, develop an innovative solution, and demonstrate it through a prototype.', eligibility: 'Students from any discipline may participate.', needs: 'A solution idea, prototype/model, and clear presentation explaining the problem, solution, and expected impact.', judging: 'Judges will evaluate:\n- Innovation & originality\n- Feasibility\n- Potential impact\n- Relevance to the given theme\n- Prototype quality\n- Presentation clarity', information: '', themes: ['AI Agents & Automation', 'Sustainability', 'Healthcare', 'Education', 'Cybersecurity', 'Smart Cities', 'Agriculture', 'Accessibility'], rules: ['Teams may have 1–4 members.', 'The solution must be relevant to the given theme.', 'The proposed solution must be original.', 'A prototype/model must be presented.', 'Participants must clearly explain the problem, solution, and impact.', 'Research and external resources must be properly acknowledged.', 'Judges\' decisions will be final.'] },
  { id: '03', category: 'TECHNICAL', title: 'RE:UX', type: 'UI/UX Reverse Engineering', description: 'Get a theme on the spot and recreate it as a polished frontend experience.', objective: 'Participants receive a theme on the spot and must design and build a frontend that matches the given concept while demonstrating creativity, usability, and visual accuracy.', eligibility: 'Open to students interested in UI/UX design, frontend development, and creative technology.', needs: '', judging: 'Judges will evaluate:\n- Theme understanding\n- UI/UX design quality\n- Visual accuracy\n- Creativity\n- Usability\n- Frontend implementation\n- Overall presentation', information: '', rules: ['The theme will be provided on the spot.', 'Participants must create the frontend based on the given theme.', 'Participants may use Figma, Adobe XD, Penpot, Sketch, VS Code, or other suitable design/development tools.', 'Original work is required.', 'Teams may have 1–4 members.', 'Final design/frontend must be presented within the allotted time.', 'Judges\' decisions will be final.'] },
  { id: '04', category: 'TECHNICAL', title: 'ODESSYTECH', type: 'AI Prompt Battle', description: 'Master the art of prompt engineering and turn ideas into precise, useful AI outputs.', objective: 'Challenge participants to design effective prompts that guide AI systems to produce accurate, creative, and useful results.', eligibility: 'Open to students interested in AI, prompt engineering, and creative problem solving.', needs: 'Knowledge of prompt engineering, logical thinking, creativity, and problem-solving skills.', judging: 'Participants will be evaluated based on prompt quality, clarity, reasoning, creativity, output accuracy, effectiveness, and responsible AI usage.', information: '', rules: ['Participants must create their own prompts.', 'Teams may have 1–4 members.', 'Prompts must be relevant to the given challenge.', 'No harmful, inappropriate, or unsafe content.', 'Participants must explain their prompting approach and reasoning.', 'Judges\' decisions will be final.'] },
  { id: '05', category: 'TECHNICAL', title: 'SQL BATTLE ROYAL', type: 'SQL Battle', description: 'Battle through challenging SQL problems where speed, accuracy, and query skills decide the winner.', objective: 'Test participants\' SQL knowledge and problem-solving skills through a series of database challenges.', eligibility: 'Open to students with basic knowledge of SQL and databases.', needs: '', judging: 'Participants will be evaluated based on query correctness, accuracy, efficiency, problem-solving approach, and completion time.', information: '', rules: ['Teams may have 1–4 members.', 'Participants must solve the given SQL challenges.', 'Queries must be correct and produce the required results.', 'Only the provided database/schema may be used.', 'Plagiarism or unfair practices will lead to disqualification.', 'Judges\' decisions will be final.'] },
  { id: '06', category: 'NON-TECHNICAL', title: 'Hint Crackers', type: 'Storytelling by Keywords', description: 'Turn a handful of unexpected words into a story no one saw coming.', objective: 'Create a memorable narrative from a shared set of keywords.', eligibility: 'Open to all students and storytellers.', needs: 'Nothing but a voice, imagination, and a point of view.', judging: 'Narrative arc, originality, delivery, and connection with the room.', information: 'Keywords are revealed on stage and stories are told live.', rules: ['Solo or team of up to 4', 'Stories must be original', 'Performance time is limited'] },
  { id: '07', category: 'NON-TECHNICAL', title: 'Tech-it-out', type: 'Just a Minute', description: 'Think fast, speak clearly, and stay with the thought before the clock catches you.', objective: 'Hold the room with an impromptu one-minute speech.', eligibility: 'Open to students from every department.', needs: 'Confidence, clarity, and a willingness to improvise.', judging: 'Fluency, relevance, structure, and composure.', information: 'Participants receive a topic and one minute to make it matter.', rules: ['No prepared scripts', 'One participant per turn', 'Time penalties apply'] },
  { id: '08', category: 'NON-TECHNICAL', title: 'Connexion', type: 'Connection Challenge', description: 'Spot the hidden link between clues, images, names, and moments.', objective: 'Identify the common thread before the other teams do.', eligibility: 'Open to students; teams of 1–4.', needs: 'A team name and a quick eye for patterns.', judging: 'Correct answers and speed across multiple rounds.', information: 'Visual, audio, and cultural clues build toward a final connection.', rules: ['Teams may have 1–4 members', 'No phones during rounds', 'Answer sheets are final'] },
  { id: '09', category: 'NON-TECHNICAL', title: 'Chitiram: The Visual Saga', type: 'Video Clip', description: 'Read the frame, hear the clue, and interpret the visual story in front of you.', objective: 'Identify and interpret a sequence of visual and video clues.', eligibility: 'Open to every student team.', needs: '', judging: 'Accuracy, interpretation, and response time.', information: 'Short clips and stills lead through a fast-paced visual quiz.', rules: ['Teams may have 1–4 members', 'No recording during the event', 'Tie-breakers use sudden-death clues'] },
  { id: '10', category: 'NON-TECHNICAL', title: 'THE DAL: THE JOURNEY OF KNOWLEDGE', type: 'On the Spot Quiz', description: 'A fast-paced on-the-spot general knowledge quiz where quick thinking and knowledge lead to victory.', objective: 'Challenge participants with questions covering general knowledge, current affairs, science, culture, sports, and unexpected topics.', eligibility: 'Open to all college students.', needs: '', judging: 'Based on correct answers, speed, and performance in the final round.', information: '', rules: ['Teams may have 1–4 members.', 'Questions will be asked on the spot.', 'No electronic aids or external assistance.', 'Participants must answer within the allotted time.', "The quizmaster's decision is final."] },
]

export type Coordinator = {
  name: string
  label: 'HEAD OF DEPARTMENT OF CSE' | 'FACULTY COORDINATOR' | 'STUDENT COORDINATOR'
  designation: string
  department: string
  year?: string
  role: string
  bio: string
  contact?: string
  image: string
}

export const coordinators: Coordinator[] = [
  { name: 'Mrs T.GEETHA', label: 'HEAD OF DEPARTMENT OF CSE', designation: 'Head of Department', department: 'CSE', role: 'Academic direction', bio: 'Guiding the academic vision and collaborative spirit behind UNIQUE 2K26.', image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85' },
  { name: 'Mrs S.JAYAPRADHA', label: 'FACULTY COORDINATOR', designation: 'Faculty Coordinator', department: 'CSE', role: 'Faculty coordination', bio: 'Supporting every moving part with care, clarity, and campus experience.', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85' },
  { name: 'Mrs B.DEEPIKA', label: 'FACULTY COORDINATOR', designation: 'Faculty Coordinator', department: 'CSE', role: 'Faculty coordination', bio: 'Connecting teams, mentors, and participants across the symposium.', image: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=85' },
  { name: 'Mr R.DEVANAND', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Bringing student energy, ideas, and momentum to the event floor.', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=85' },
  { name: 'Mr R.PAVAN', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Helping every participant find their place in the UNIQUE experience.', image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=85' },
  { name: 'Mr R.SUBASH', label: 'STUDENT COORDINATOR', designation: 'Student Coordinator', department: 'CSE', year: 'IV Year', role: 'Student coordination', bio: 'Turning plans into welcoming, thoughtful campus moments.', image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=85' },
]

export const faqs = [
  ['What is UNIQUE 2K26?', 'UNIQUE 2K26 is a college symposium bringing students together through technology, creativity, innovation, and entertainment.'],
  ['What is the maximum team size?', 'Teams may have 1–4 members. Individuals are welcome to participate.'],
  ['Can a team participate in more than one event?', 'Yes. Each team may select one Technical event and one Non-Technical event.'],
  ['Can we choose both a technical and non-technical event?', 'Yes. The participation rule is one Technical + one Non-Technical event per team.'],
  ['What are the technical events?', 'Glitch Verse, Mind Spark, RE: UX, AI Prompt Battle, and SQL Battle Royal.'],
  ['What are the non-technical events?', 'Hint Crackers, Tech-it-out, Connexion, Video Clip, and On the Spot Quiz.'],
  ['Can I participate individually?', 'Yes. Individual participation is welcome, and teams may have 1–4 members.'],
  ['How do I register?', 'Use the global REGISTER NOW link near the hero, navbar, or registration section.'],
  ['When will the schedule be announced?', 'The one-day schedule, timings, and venue will be announced soon.'],
]
